=== GossJS/15092017-BazhanPavel/22092017/part2/BazhanP_part2.xsd
<?xml version="1.0" encoding="UTF-8" ?>

<xs:schema 
	xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="table">
	   <xs:complexType>
	   		<xs:sequence>
	        	<xs:element name="student" maxOccurs="unbounded">
	        		<xs:complexType>
		        		<xs:sequence>
				        	<xs:element name="grade" maxOccurs="4" minOccurs="1">
				        		<xs:complexType>
					        		<xs:simpleContent>
					        			<xs:extension base="xs:integer">
								        	<xs:attribute name="subject" type="xs:string"/>
								        </xs:extension>
					        		</xs:simpleContent>
				        		</xs:complexType>
				        	</xs:element>
				        </xs:sequence>
		        		<xs:attribute name="name" type="xs:string"/>
	        		</xs:complexType>
	        	</xs:element>
	        </xs:sequence>
	   </xs:complexType>
	</xs:element>
</xs:schema>

=== GossJS/15092017-BazhanPavel/22092017/part2/BazhanP_part2.xml
<?xml version="1.0" encoding="UTF-8" ?>

<table 
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="BazhanP_part2.xsd">
    <student name = "Иванов">
		<grade subject="Мультимедиа">3</grade>
		<grade subject="Веб-дизайн">3</grade>
		<grade subject="Графика">5</grade>
	</student>
	<student name = "Петрова">
		<grade subject="Мультимедиа">3</grade>
		<grade subject="Веб-дизайн">4</grade>
		<grade subject="Графика">5</grade>
		<grade subject="Логика">5</grade>
	</student>
	<student name = "Сидоренко">
		<grade subject="Мультимедиа">3</grade>
		<grade subject="Веб-дизайн">4</grade>
		<grade subject="Графика">5</grade>
		<grade subject="Логика">4</grade>
	</student>
</table>
